### ISSUE TITLE
Pre-release task list

### ISSUE THREAD

**Issue by tanelj** [Voog/design-reykjavik#1]
- [x] HTML for blog "Read more" link is broken - space is missing: `<a href="/blog/see-on-minu-kolmas-pealkiri-lt-br-gt"class="read-more">Read more</a>`
- [x] New `{{ site.stats_header }}` tag is missing should be placed just before `</head>` tag
- [x] Search place holder is misplaced in mobile view
- [x] Search results pagination jumps to top after loading next page (FF)
- [x] Background should be only in `<pre>` tag not `<code>` tag.
- [x] There should be padding for `pre` tag
- [x] When there is multi line text or bigger logo in site header then its ugly in mobile views.
- [x] Article tag icon is shifted in edit mode (ok in preview)
- [x] Icons are needed for dark color schema
- [x] Empty content area "drag some content here" message is same color as background in dark schema
- [x] Common page - if slogan area is missing then body area should be place better
- [x] `http://static.voog.com/libs/edicy-search` is hardcoded should be `{{`site.static_asset_host }}/libs/edicy-search`
- [x] Use lates Edicy tools "/assets/admin/tools/**0.1.3**/edicy-tools.js"
- [x] IE9: there is bottom scroll in IE (content is wider than window in small screens)
- [x] IE9: Lang menu is in wrong place
  ![reykjavik-ie9-langmenu](https://cloud.githubusercontent.com/assets/378755/3415523/e7cd96e0-fe21-11e3-89f7-81310a8344cc.png)
- [x] IE9: Place holders are missing in preview and public modes
- [x] IE11: There is no margin on left and right side. Also slogan is wider than in other browsers:
  ![reykjavik-ie11-no-margin](https://cloud.githubusercontent.com/assets/378755/3424364/6178d936-ffcc-11e3-8b33-e226b221a8ff.png)
- [x] IE11: search placeholder is miss placed:

![reykjavik-ie11-search-misplaced-placeholder](https://cloud.githubusercontent.com/assets/378755/3424365/70eb0a60-ffcc-11e3-83c1-94b327ed5b00.png)
- [x] Chrome: When design background colour is set to dark (text is white) then when moving from page to page, there is something loading slowly: text appears in black first.
